[package]
name = "kinema-lint"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kinema-syntax = { workspace = true }
kinema-elab = { workspace = true }
kinema-kicad = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
